import Head from "next/head";
import React from "react";
import BannerViceo from "../components/banner/BannerViceo";
import CopyrightFooter from "../components/copyright/CopyrightFooter";
import HeaderTransparent from "../components/header/HeaderTransparent";

function indexVideo() {
  return (
    <>
      <Head>
        <title>PicsZen - Portfolio React Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
      <HeaderTransparent />
      <BannerViceo />
      <CopyrightFooter />
    </>
  );
}

export default indexVideo;
