import Head from "next/head";
import { useEffect, useState } from "react";

function CounterNum() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCount((count) => count + 1);
    }, 40);
    if (count === 100) {
      clearInterval(interval);
    }

    return () => clearInterval(interval);
  }, [count]);

  return (
    <>
      <Head>
        {count === 100 ? (
          <title>PicsZen - Portfolio React Template</title>
        ) : (
          <title>Loading</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
      <div className={count === 100 ? "preloader active" : "preloader"}>
        <div className={count === 100 ? "hide" : ""}>
          <span className="counter">{count}</span>
        </div>
      </div>
    </>
  );
}

function Preloader({}) {
  return (
    <>
      <CounterNum />
    </>
  );
}
export default Preloader;
